### PR TITLE
Museum mode

### PR DESCRIPTION
**Pull request by noahmalmed**
Add custom features for a mapping historic skies museum mode. Please not that I made a new branch on the zooniverse/mobile repo that I'm merging this into.

Invision Mock-ups:  https://projects.invisionapp.com/d/main#/console/15642822/339630114/preview

- Update the drawing classifier to have a "dark mode" (see invision)
- Update the drawing classifier to remove any navigation options from the page.

# Review Checklist

- [x] Does it work in Android and iOS?
- [x] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] Are tests passing?

### CODE REVIEW

**Comment by wgranger** [comment]
I'm unable to access Mapping Historical Skies on this branch. Do I need to be added to the project?

**Comment by noahmalmed** [comment]
@wgranger it should be in Beta

**Comment by wgranger** [comment]
All good. Had to switch into 'production.' Also, I think an older version of the `museum-mode` branch was conflicting with this somehow on my local machine, so I pulled down the branch fresh. I'm seeing the dark theme now.

**Comment by wgranger** [comment]
Code changes here look good. How have we been switching over to this brach for public demos?

**Comment by noahmalmed** [comment]
Added a scheme to the xcode project called 'museum' 
image

To run this code on device, switch to the 'museum' mode and select the device and press the run button.

**Comment by noahmalmed** [comment]
So to run this as a demo, run this branch as explained above

**Comment by wgranger** [comment]
How does this account for the iPads we use with floor demos? Unless I'm mistaken, xCode wasn't installed on those devices.

**Pull request merged**
