### PR TITLE
Display mobile projects

### PR DESCRIPTION
**Pull request by noahmalmed**
Describe your changes.
- Only show `launch_approved: true` projects to ensure all mobile projects are in fact mobile ready and verified by the team.
- Fix some file structure issues with the xcode project file caused from updating from xcode 8 to 9.
- Remove duplicate listing of `panoptes-client` in `package.json`
- Committing `package-lock.json` per https://docs.npmjs.com/files/package-lock.json
# Review Checklist

- [x] Does it work in Android and iOS?
- [x] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] Are tests passing?

### CODE REVIEW

**Comment by wgranger** [comment]
Good call on the package.lock. That's a good resource with the info on committing. As you're modifying the package.json, could you update the `panoptes-client`? We should be on 9.2.1

**Comment by noahmalmed** [comment]
Wait... 9.2.1? I tried using that version and npm says that it doesn't exist. Did you mean 2.9.1?

**Comment by wgranger** [comment]
Yes! My bad, it is 2.9.1

**Comment by noahmalmed** [comment]
@wgranger updated per your request

**Comment by wgranger** [comment]
LGTM

**Pull request merged**
